// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/split.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplexName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexName) Reset() {
	*x = ComplexName{}
	mi := &file_proto_split_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexName) ProtoMessage() {}

func (x *ComplexName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_split_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexName.ProtoReflect.Descriptor instead.
func (*ComplexName) Descriptor() ([]byte, []int) {
	return file_proto_split_proto_rawDescGZIP(), []int{0}
}

func (x *ComplexName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Split struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ComplexName   *ComplexName           `protobuf:"bytes,2,opt,name=complex_name,json=complexName,proto3" json:"complex_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Split) Reset() {
	*x = Split{}
	mi := &file_proto_split_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Split) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Split) ProtoMessage() {}

func (x *Split) ProtoReflect() protoreflect.Message {
	mi := &file_proto_split_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Split.ProtoReflect.Descriptor instead.
func (*Split) Descriptor() ([]byte, []int) {
	return file_proto_split_proto_rawDescGZIP(), []int{1}
}

func (x *Split) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Split) GetComplexName() *ComplexName {
	if x != nil {
		return x.ComplexName
	}
	return nil
}

var File_proto_split_proto protoreflect.FileDescriptor

var file_proto_split_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x05, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78,
	0x4e, 0x61, 0x6d, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x73, 0x63, 0x68, 0x61, 0x6c, 0x6f, 0x6c, 0x6f, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_split_proto_rawDescOnce sync.Once
	file_proto_split_proto_rawDescData []byte
)

func file_proto_split_proto_rawDescGZIP() []byte {
	file_proto_split_proto_rawDescOnce.Do(func() {
		file_proto_split_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_split_proto_rawDesc), len(file_proto_split_proto_rawDesc)))
	})
	return file_proto_split_proto_rawDescData
}

var file_proto_split_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_split_proto_goTypes = []any{
	(*ComplexName)(nil), // 0: ComplexName
	(*Split)(nil),       // 1: Split
}
var file_proto_split_proto_depIdxs = []int32{
	0, // 0: Split.complex_name:type_name -> ComplexName
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_split_proto_init() }
func file_proto_split_proto_init() {
	if File_proto_split_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_split_proto_rawDesc), len(file_proto_split_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_split_proto_goTypes,
		DependencyIndexes: file_proto_split_proto_depIdxs,
		MessageInfos:      file_proto_split_proto_msgTypes,
	}.Build()
	File_proto_split_proto = out.File
	file_proto_split_proto_goTypes = nil
	file_proto_split_proto_depIdxs = nil
}
