// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/tag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           int32                  `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Tag2          int32                  `protobuf:"varint,16,opt,name=tag2,proto3" json:"tag2,omitempty"`
	Tag3          int32                  `protobuf:"varint,2048,opt,name=tag3,proto3" json:"tag3,omitempty"`
	Tag4          int32                  `protobuf:"varint,262144,opt,name=tag4,proto3" json:"tag4,omitempty"`
	Tag5          int32                  `protobuf:"varint,33554432,opt,name=tag5,proto3" json:"tag5,omitempty"`
	Tag6          int32                  `protobuf:"varint,536870911,opt,name=tag6,proto3" json:"tag6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tags) Reset() {
	*x = Tags{}
	mi := &file_proto_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tags) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Tags) GetTag2() int32 {
	if x != nil {
		return x.Tag2
	}
	return 0
}

func (x *Tags) GetTag3() int32 {
	if x != nil {
		return x.Tag3
	}
	return 0
}

func (x *Tags) GetTag4() int32 {
	if x != nil {
		return x.Tag4
	}
	return 0
}

func (x *Tags) GetTag5() int32 {
	if x != nil {
		return x.Tag5
	}
	return 0
}

func (x *Tags) GetTag6() int32 {
	if x != nil {
		return x.Tag6
	}
	return 0
}

var File_proto_tag_proto protoreflect.FileDescriptor

var file_proto_tag_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x86, 0x01, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x32, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x61, 0x67, 0x32,
	0x12, 0x13, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x33, 0x18, 0x80, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x61, 0x67, 0x33, 0x12, 0x14, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x34, 0x18, 0x80, 0x80,
	0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x61, 0x67, 0x34, 0x12, 0x15, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x35, 0x18, 0x80, 0x80, 0x80, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x35, 0x12, 0x16, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x36, 0x18, 0xff, 0xff, 0xff, 0xff, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x61, 0x67, 0x36, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x73, 0x63, 0x68, 0x61, 0x6c,
	0x6f, 0x6c, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_tag_proto_rawDescOnce sync.Once
	file_proto_tag_proto_rawDescData []byte
)

func file_proto_tag_proto_rawDescGZIP() []byte {
	file_proto_tag_proto_rawDescOnce.Do(func() {
		file_proto_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)))
	})
	return file_proto_tag_proto_rawDescData
}

var file_proto_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_tag_proto_goTypes = []any{
	(*Tags)(nil), // 0: Tags
}
var file_proto_tag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tag_proto_init() }
func file_proto_tag_proto_init() {
	if File_proto_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tag_proto_goTypes,
		DependencyIndexes: file_proto_tag_proto_depIdxs,
		MessageInfos:      file_proto_tag_proto_msgTypes,
	}.Build()
	File_proto_tag_proto = out.File
	file_proto_tag_proto_goTypes = nil
	file_proto_tag_proto_depIdxs = nil
}
